# Generated by Django 5.1.2 on 2024-10-14 06:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medikua',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=100)),
                ('jaiotze_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=100)),
                ('jaiotze_data', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Zitak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zita_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('medikukodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikazioaOsakidetza.medikua')),
                ('pazientekodea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplikazioaOsakidetza.paziente')),
            ],
        ),
    ]
